name: Build and Push Nginx Static Site

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker file
        run: |
          echo "Building Docker image for static hosting..."
          cat <<EOF > Dockerfile
          # Use official nginx image
          FROM nginx:alpine

          # Remove default nginx static files
          RUN rm -rf /usr/share/nginx/html/*

          # Copy index.html from repo to nginx html directory
          COPY index.html /usr/share/nginx/html/index.html

          # Expose port 80
          EXPOSE 80

          # Run nginx in the foreground
          CMD ["nginx", "-g", "daemon off;"]
          EOF

      - name: Build Docker Image
        run: |
          echo "Building Docker image arsalaan272/frontend:v11 ..."
          docker build -t arsalaan272/frontend:v11 .

      - name: Push Docker Image to Docker Hub
        run: |
          echo "Pushing image to Docker Hub..."
          docker push arsalaan272/frontend:v11

      - name: Print Docker Image URL
        run: |
          echo "âœ… Image successfully pushed: docker.io/arsalaan272/frontend:v11"
